/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        colors: {
          "Foundation/brand-primarypurple": "#7000ff",
          "Foundation/brand-washedpurple": "#b6b2ff",
          "Foundation/brand-primaryblue": "#0469ff",
          "Foundation/brand-dark": "#030014",
          "Foundation /Purple/purple-50": "#efe6fd",
          "Foundation /Purple/purple-100": "#ceb0fa",
          "Foundation /Purple/purple-200": "#b78af7",
          "Foundation /Purple/purple-300": "#9654f4",
          "Foundation /Purple/purple-400": "#8133f1",
          "Foundation /Purple/purple-500": "#6200ee",
          "Foundation /Purple/purple-600": "#5900d9",
          "Foundation /Purple/purple-700": "#4600a9",
          "Foundation /Purple/purple-800": "#360083",
          "Foundation /Purple/purple-900": "#290064",
          "Foundation /Washed-purple/washed-purple-50": "#f8f7ff",
          "Foundation /Washed-purple/washed-purple-100": "#e8e7ff",
          "Foundation /Washed-purple/washed-purple-200": "#dddcff",
          "Foundation /Washed-purple/washed-purple-300": "#cecbff",
          "Foundation /Washed-purple/washed-purple-400": "#c5c1ff",
          "Foundation /Washed-purple/washed-purple-500": "#b6b2ff",
          "Foundation /Washed-purple/washed-purple-600": "#a6a2e8",
          "Foundation /Washed-purple/washed-purple-700": "#817eb5",
          "Foundation /Washed-purple/washed-purple-800": "#64628c",
          "Foundation /Washed-purple/washed-purple-900": "#4c4b6b",
          "Foundation /primary-blue/primary-blue-50": "#e6f0ff",
          "Foundation /primary-blue/primary-blue-100": "#b1d1ff",
          "Foundation /primary-blue/primary-blue-200": "#8cbaff",
          "Foundation /primary-blue/primary-blue-300": "#579bff",
          "Foundation /primary-blue/primary-blue-400": "#3687ff",
          "Foundation /primary-blue/primary-blue-500": "#0469ff",
          "Foundation /primary-blue/primary-blue-600": "#0460e8",
          "Foundation /primary-blue/primary-blue-700": "#034bb5",
          "Foundation /primary-blue/primary-blue-800": "#023a8c",
          "Foundation /primary-blue/primary-blue-900": "#022c6b",
          "Foundation /primary-purple/primary-purple-50": "#f1e6ff",
          "Foundation /primary-purple/primary-purple-100": "#d3b0ff",
          "Foundation /primary-purple/primary-purple-200": "#bd8aff",
          "Foundation /primary-purple/primary-purple-300": "#9f54ff",
          "Foundation /primary-purple/primary-purple-400": "#8d33ff",
          "Foundation /primary-purple/primary-purple-500": "#7000ff",
          "Foundation /primary-purple/primary-purple-600": "#6600e8",
          "Foundation /primary-purple/primary-purple-700": "#5000b5",
          "Foundation /primary-purple/primary-purple-800": "#3e008c",
          "Foundation /primary-purple/primary-purple-900": "#2f006b",
          "Foundation /Neutrals/neutrals-50": "#e6e6e8",
          "Foundation /Neutrals/neutrals-100": "#b1b0b6",
          "Foundation /Neutrals/neutrals-200": "#8b8a93",
          "Foundation /Neutrals/neutrals-300": "#565462",
          "Foundation /Neutrals/neutrals-400": "#353343",
          "Foundation /Neutrals/neutrals-500": "#030014",
          "Foundation /Neutrals/neutrals-600": "#030012",
          "Foundation /Neutrals/neutrals-700": "#02000e",
          "Foundation /Neutrals/neutrals-800": "#02000b",
          "Foundation /Neutrals/neutrals-900": "#010008",
          "Foundation /Neutrals/neutrals-1": "#ffffff",
          "Foundation /Neutrals/neutrals-2": "#fcfcfc",
          "Foundation /Neutrals/neutrals-3": "#f5f5f5",
          "Foundation /Neutrals/neutrals-4": "#f0f0f0",
          "Foundation /Neutrals/neutrals-5": "#d9d9d9",
          "Foundation /Neutrals/neutrals-6": "#bfbfbf",
          "Foundation /Neutrals/neutrals-7": "#8c8c8c",
          "Foundation /Neutrals/neutrals-8": "#595959",
          "Foundation /Neutrals/neutrals-9": "#454545",
          "Foundation /Neutrals/neutrals-10": "#262626",
          "Foundation /Neutrals/neutrals-11": "#1f1f1f",
          "Foundation /Neutrals/neutrals-12": "#141414",
          "Foundation /Neutrals/neutrals-13": "#000000"
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}